config/routes.rb
VirtualToken::Application.routes.draw do
  devise_for :users
  resources :tokens do
    resources :token_requests, :as => :requests do
      member do
        put 'move'
      end
    end
  end
  root :to => 'tokens#new'
end

app/models/token.rb
class Token < ActiveRecord::Base
  def self.generate_slug(name)
    name.to_s.downcase.gsub(/\W+/, '-').gsub(/(^-|-$)/, '')
  end

  has_many :requests, :class_name => 'TokenRequest', :inverse_of => :token,
    :dependent => :destroy, :order => 'position ASC'

  before_validation :set_slug, :on => :create

  validates_presence_of :name, :slug
  validates_uniqueness_of :name

  def self.other_tokens(t)
    Token.order('updated_at desc').where( 'tokens.id != ?', t).limit(10)
  end

  def to_param
    slug
  end

  def claimed?
    requests.any?
  end

  def current_request(reload = false)
    requests(reload).first
  end

  def claimed_by
    current_request ? current_request.user : nil
  end

  def claimed_at
    current_request ? current_request.claim_granted_at : nil
  end

  def claim_purpose
    current_request ? current_request.purpose : nil
  end

  def queue
    requests.where(:claim_granted_at => nil)
  end

  def has_queue?
    queue.any?
  end

  def update_queue
    if _current_request = current_request(true)
      _current_request.grant_claim
    end
  end

  private

  def set_slug
    self.slug = Token.generate_slug(name)
  end
end

app/models/token_request.rb
class TokenRequest < ActiveRecord::Base
  belongs_to :user
  belongs_to :token, :inverse_of => :requests
  acts_as_list :scope => :token
  TOP_OF_QUEUE = 2 # position 1 is the current request

  validates_presence_of :user
  validates_presence_of :token
  validates_presence_of :purpose

  delegate :name, :to => :user, :prefix => true

  after_create :update_token

  def update_token
    token.touch
  end

  def grant_claim
    unless claim_granted?
      update_attribute(:claim_granted_at, Time.now)
      TokenRequestNotification.claim_granted(self).deliver
    end
  end

  def revoke_claim
    update_attribute(:claim_granted_at, nil)
  end

  def claim_granted?
    claim_granted_at.present?
  end
  
  def move(where)
    case where
    when 'top'
      insert_at TOP_OF_QUEUE
    when 'bottom'
      move_to_bottom
    when 'up'
      move_higher unless higher_item.first?
    when 'down'
      move_lower
    when 'claim'
      token.current_request.revoke_claim
      move_to_top
      grant_claim
    end
  end
end

app/models/token_request_queue_observer.rb
class TokenRequestQueueObserver < ActiveRecord::Observer
  observe :token_request

  def after_create(request)
    request.token.update_queue
  end
  alias_method :after_destroy, :after_create
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
    :trackable, :validatable, :confirmable, :lockable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me

  validates_presence_of :name

  def to_s
    "#{name} <#{email}>"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'
  before_filter :authenticate_user!
end

app/controllers/token_requests_controller.rb
class TokenRequestsController < ApplicationController
  skip_before_filter :authenticate_user!, :only => :index

  def index
    redirect_to token_path(params[:token_id])
  end

  def create
    TokenRequest.create!(token_params)
    redirect_to token_path(params[:token_id])
  rescue ActiveRecord::RecordInvalid => e
    @token = token_params[:token]
    @new_token_request = e.record
    render 'tokens/show'
  end

  def destroy
    TokenRequest.destroy(params[:id])
    redirect_to token_path(params[:token_id])
  end
  
  def move
    token_request = TokenRequest.find(params[:id])
    token_request.move(params[:where])
    redirect_to token_path(params[:token_id])
  end

  private

  def token_params
    return @token_params unless @token_params.nil?
    p = params[:token_request] || {}
    p.merge!(:token => Token.find_by_slug!(params[:token_id]))
    p.merge!(:user => current_user)
    @token_params = p
  end
end

app/controllers/tokens_controller.rb
class TokensController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound do
    flash[:error] = "Token #{params[:id]} not found."
    redirect_to '/tokens'
  end

  def new
    @token = Token.new
  end

  def index
    @tokens = Token.all(:order => 'updated_at desc')
  end

  def destroy
    begin
      Token.transaction do
        @token = Token.find_by_slug!(params[:id])
        raise ActiveRecord::ActiveRecordError if @token.claimed?
        @token.destroy
        flash[:notice] = "Destroyed the #{params[:id]} token."
      end
    rescue ActiveRecord::ActiveRecordError
      flash[:error] = "Unable to destroy the #{params[:id]} token."
    end
    redirect_to '/tokens'
  end

  def create
    token = Token.create!(params[:token])
    redirect_to token_path(token)
  rescue ActiveRecord::RecordInvalid => e
    @token = e.record
    render :action => :new
  end

  def show
    @token = Token.find_by_slug!(params[:id])
    @other_tokens = Token.other_tokens(@token)
    @new_token_request = TokenRequest.new
  end

  def update
    token = Token.find(params[:id])
    token.update_attributes!(params[:token])
  rescue ActiveRecord::StaleObjectError
    flash[:error] = "The token has already been updated by another user."
  ensure
    redirect_to token_path(token)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tokens_helper.rb
module TokensHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VirtualToken</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <% if flash[:notice] %>
    <p class="notice"><%= flash[:notice] %></p>
  <% end %>

  <% if flash[:alert] %>
    <p class="alert"><%= flash[:alert] %></p>
  <% end %>

  <% if flash[:error] %>
    <p class="error"><%= flash[:error] %></p>
  <% end %>

<%= yield %>

</body>
</html>

app/views/token_request_notification/claim_granted.text.erb
Hello <%= @user.name %>,

It's your turn with the <%= @token.name %> token.
<<%= token_url(@token) %>>

You reserved this token in order to:

<%= @token_request.purpose %>

If you no longer need the token, or if you will be unable to act on the token
for a long time, please be sure to visit the token page and release it for the
next person in line.

app/views/tokens/new.html.erb
<%= form_for @token do |f| %>
  <% if @token.errors.any? %>
    <p><%= @token.errors.full_messages.join('</p><p>') -%></p>
  <% end %>
  <p><%= f.label :name -%>
  <%= f.text_field :name -%>
  <%= submit_tag 'Create Token' -%></p>
<% end %>

app/views/tokens/show.html.erb
<h1><%= @token.name %></h1>

<% if @token.claimed? %>
  <div id="token-claim-info">
    <p>This token has been claimed by <%= @token.claimed_by %> for <%= time_ago_in_words(@token.claimed_at) %>.</p>
    <blockquote>
      <%= @token.claim_purpose %>
    </blockquote>
    <%= button_to 'Release Token', token_request_path(@token, @token.current_request),
    :method => :delete,
    :confirm => (@token.claimed_by == current_user ? nil : \
                 'You are not the owner of the current claim. ' +
                 'Are you sure you want to release the token?') %>
  </div>
<% end %>

<h2>Token Queue</h2>

<%= form_for @new_token_request, :url => token_requests_path(@token) do |f| %>
  <fieldset>
    <legend>Request Token</legend>
    <% if @new_token_request.errors.any? %>
      <div class="error">
        <p>The token request could not be saved because:</p>
        <ul>
          <% @new_token_request.errors.full_messages.each do |m| %>
            <li><%= m %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div><%= f.label :purpose %> <%= f.text_field :purpose %>
      <%= submit_tag 'Submit Request' %></div>
  </fieldset>
<% end %>

<div id="other-tokens">
  <h3><%= link_to "Other Recently Used Tokens", tokens_path %></h3>
<ul>
  <% @other_tokens.each do |token| %>
    <li><%= link_to token.name, token %></li> 
  <% end %>
</ul>
</div>

<% if @token.has_queue? %>
  <table id="token-queue">
    <thead>
      <tr>
        <th>Who</th>
        <th>Why</th>
        <th>When</th>
        <th>&nbsp;</th>
      </tr>
    </thead>
    <tbody>
      <% @token.queue.each do |token_request| %>
        <tr>
          <td><%= token_request.user_name %></td>
          <td><%= token_request.purpose %></td>
          <td><%= time_ago_in_words(token_request.created_at) %> ago</td>
          <td>
            <ul>
              <% ['top', 'up', 'down', 'bottom'].each do |where| %>
                <li>
                <%= link_to where, move_token_request_path(@token, token_request, :where => where), :method => :put %>
                </li>
              <% end %>
              <li>
                <%= link_to 'claim', move_token_request_path(@token, token_request, :where => 'claim'), :method => :put, :confirm => 'Are you sure you want to be a jerk and steal the claim on the token?' %>
              </li>
              <li>
                <%= link_to 'delete', token_request_path(@token, token_request),
                  :method => :delete,
                  :confirm => (token_request.user == current_user ? nil : \
                               'You are not the owner of this request. ' +
                               'Are you sure you want to delete it?') %>
             </li>
           </ul>
         </td>
       </tr>
    <% end %>
  </table>
<% end %>